var name;
var myname="Fahad Mehmood";
var message="Hello World";
alert(message);
var student_name="fahad mehmood";
var age="20";
var course="Certified Moile and app developer";
alert(student_name);
alert(age);
alert(course);
